export const projects = [
  {
    id: 9,
    title: "ISTORE",
    style: "istore",
    descriptionKey: "projects.istore",
    link: "https://i-store-lyart.vercel.app/",
    preview: "/Istore/istore.webp",
    images: [
      "/Istore/istore.webp",
      "/Istore/istore2.jpg",
      "/Istore/istore3.jpg",
      "/Istore/istore4.jpg",
      "/Istore/istore5.jpg",
      "/Istore/istore6.jpg",
      "/Istore/istore7.jpg",
      "/Istore/istore8.jpg",
    ],
  },
  {
    id: 7,
    title: "Finance App",
    style: "finance",
    descriptionKey: "projects.finance",
    link: "https://financial-analyst.vercel.app/",
    preview: "/finance/finace_app.webp",
    images: [
      "/finance/finace_app.webp",
      "/finance/head_inform.jpg",
      "/finance/head_inform2.jpg",
      "/public/finance/head_inform3.jpg",
    ],
  },
  {
    id: 8,
    title: "AquaTrack",
    style: "aquaTrack",
    descriptionKey: "projects.aqua",
    link: "https://aqua-track-group-01.vercel.app/",
    preview: "/AquaTrack/head.webp",
    images: [
      "/AquaTrack/head.webp",
      "/AquaTrack/mainPage.jpg",
      "/AquaTrack/settings.jpg",
    ],
  },
  {
    id: 1,
    title: "WebTech",
    style: "webTech",
    descriptionKey: "projects.webTech",
    link: "https://webtech-pied.vercel.app/",
    preview: "/webtech/webtech.webp",
    images: [
      "/webtech/webtech.webp",
      "/webtech/webtech2.jpg",
      "/webtech/webtech3.jpg",
    ],
  },
  {
    id: 2,
    title: "SEO Marketing",
    style: "seo",
    descriptionKey: "projects.seo",
    link: "https://seo-marketing-rouge.vercel.app/",
    preview: "/seo/seo_m.jpg",
    images: ["/seo/seo.jpg", "/seo/seo2.jpg", "/seo/seo3.jpg", "/seo/seo4.jpg"],
  },
  {
    id: 3,
    title: "Trucks Сampers",
    style: "seo",
    descriptionKey: "projects.truck",
    link: "https://travel-trucks-wine.vercel.app/",
    preview: "/Trucks/head.jpg",
    images: ["/Trucks/head.jpg", "/Trucks/truck2.jpg", "/Trucks/truck3.jpg"],
  },
  {
    id: 4,
    title: "SparkArts",
    style: "sparkart",
    descriptionKey: "projects.sparkart",
    link: "https://dmytrok-goit.github.io/stp-7973/",
    preview: "/SparkArt/main.jpg",
    images: [
      "/SparkArt/main.jpg",
      "/SparkArt/spark2.jpg",
      "/SparkArt/spark3.jpg",
    ],
  },
  {
    id: 5,
    title: "Portfolio",
    style: "portfolio",
    descriptionKey: "projects.portfolio",
    link: "https://dmytrok-goit.github.io/project-js-group02/",
    preview: "/portfolio/head_info.jpg",
    images: [
      "/portfolio/head_info.jpg",
      "/portfolio/portfolio2.jpg",
      "/portfolio/portfolio3.jpg",
    ],
  },
  {
    id: 6,
    title: "PhoneBook",
    style: "phoneBook",
    descriptionKey: "projects.phonebook",
    link: "https://phone-book-full-stack.vercel.app/",
    preview: "/PhoneBook/mainForms.jpg",
    images: [
      "/PhoneBook/head.jpg",
      "/PhoneBook/contacts.jpg",
      "/PhoneBook/mainForms.jpg",
      "/PhoneBook/multiLang.jpg",
    ],
  },
  {
    id: 10,
    title: "Movies",
    style: "movies",
    descriptionKey: "projects.movie",
    link: "https://goit-react-hw-05-three-beige.vercel.app/",
    preview: "/movies/head.jpg",
    images: [
      "/movies/head.jpg",
      "/movies/movie info.jpg",
      "/movies/Search.jpg",
    ],
  },
];
