export const projects = [
  {
    id: 9,
    title: "ISTORE",
    style: "istore",
    key: "istore",
    link: "https://i-store-lyart.vercel.app/",
    preview: "/Istore/istore.webp",
    images: [
      "/Istore/istore.webp",
      "/Istore/istore2.webp",
      "/Istore/istore3.webp",
      "/Istore/istore4.webp",
      "/Istore/istore5.webp",
      "/Istore/istore6.webp",
      "/Istore/istore7.webp",
      "/Istore/istore8.webp",
    ],
  },
  {
    id: 7,
    title: "Finance App",
    style: "finance",
    key: "finance",
    link: "https://financial-analyst.vercel.app/",
    preview: "/finance/finace_app.webp",
    images: [
      "/finance/finace_app.webp",
      "/finance/head_inform.webp",
      "/finance/head_inform2.webp",
      "/finance/head_inform3.webp",
    ],
  },
  {
    id: 8,
    title: "AquaTrack",
    style: "aquaTrack",
    key: "aqua",
    link: "https://aqua-track-group-01.vercel.app/",
    preview: "/AquaTrack/head.webp",
    images: [
      "/AquaTrack/head.webp",
      "/AquaTrack/mainPage.webp",
      "/AquaTrack/settings.webp",
    ],
  },
  {
    id: 1,
    title: "WebTech",
    style: "webTech",
    key: "webTech",
    link: "https://webtech-pied.vercel.app/",
    preview: "/webtech/webtech.webp",
    images: [
      "/webtech/webtech.webp",
      "/webtech/webtech2.jpg",
      "/webtech/webtech3.jpg",
    ],
  },
  {
    id: 2,
    title: "SEO Marketing",
    style: "seo",
    key: "seo",
    link: "https://seo-marketing-rouge.vercel.app/",
    preview: "/seo/seo_m.webp",
    images: [
      "/seo/seo.webp",
      "/seo/seo2.webp",
      "/seo/seo3.webp",
      "/seo/seo4.webp",
    ],
  },
  {
    id: 10,
    title: "Dudeshape",
    style: "dudeshape",
    key: "dudeshape",
    link: "https://dudeshape-eight.vercel.app/",
    preview: "/furniture/futniture.jpg",
    images: [
      "/furniture/futniture.jpg",
      "/furniture/futniture1.jpg",
      "/furniture/futniture2.jpg",
    ],
  },
  {
    id: 3,
    title: "Trucks Campers",
    style: "trucks",
    key: "truck",
    link: "https://travel-trucks-wine.vercel.app/",
    preview: "/Trucks/head.jpg",
    images: ["/Trucks/head.jpg", "/Trucks/truck2.jpg", "/Trucks/truck3.jpg"],
  },
  {
    id: 4,
    title: "SparkArts",
    style: "sparkart",
    key: "sparkart",
    link: "https://dmytrok-goit.github.io/stp-7973/",
    preview: "/SparkArt/main.jpg",
    images: [
      "/SparkArt/main.jpg",
      "/SparkArt/spark2.jpg",
      "/SparkArt/spark3.jpg",
    ],
  },
  {
    id: 5,
    title: "Portfolio",
    style: "portfolio",
    key: "portfolio",
    link: "https://dmytrok-goit.github.io/project-js-group02/",
    preview: "/portfolio/head_info.jpg",
    images: [
      "/portfolio/head_info.jpg",
      "/portfolio/portfolio2.jpg",
      "/portfolio/portfolio3.jpg",
    ],
  },
  {
    id: 6,
    title: "PhoneBook",
    style: "phoneBook",
    key: "phonebook",
    link: "https://phone-book-full-stack.vercel.app/",
    preview: "/PhoneBook/mainForms.jpg",
    images: [
      "/PhoneBook/head.jpg",
      "/PhoneBook/contacts.jpg",
      "/PhoneBook/mainForms.jpg",
      "/PhoneBook/multiLang.jpg",
    ],
  },
  {
    id: 10,
    title: "Movies",
    style: "movies",
    key: "movie",
    link: "https://goit-react-hw-05-three-beige.vercel.app/",
    preview: "/movies/head.jpg",
    images: [
      "/movies/head.jpg",
      "/movies/movie info.jpg",
      "/movies/Search.jpg",
    ],
  },
];
